In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_recall_curve
import os

In [2]:
!pip install tensorflow
!pip install keras
!pip install torch
!pip install h5py


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 3.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 54.7 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 52.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 63.3 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 4.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 68.7 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 47.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 45.4 MB/s eta 0:00:00:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 34.7 MB/s eta 0:00:00:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 3.4 MB/s eta 0:00:00
  

In [3]:
model_rgb_path = "/workspaces/IDS705_ML_Team9/deploy_resnet_model_140K_alldata_rgb.h5"
weights_rgb_path = "/workspaces/IDS705_ML_Team9/deploy_resnet_model_140K_alldata_rgb_weights.h5"

# load the model using h5py
import h5py
model_rgb = h5py.File(model_rgb_path, 'r')
model_rgb_weights = h5py.File(weights_rgb_path, 'r')

# load the model using keras
from keras.models import model_from_json
import tensorflow.keras as keras

# Load the h5 model file
model = keras.models.load_model(model_rgb_path)

# Print the model summary
model.summary()


2023-04-18 02:50:06.408964: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-18 02:50:06.463919: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-18 02:50:06.464910: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-18 02:50:07.505498: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-18 02:50:08.572625: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for ho

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 2048)              23587712  
                                                                 
 flatten_1 (Flatten)         (None, 2048)              0         
                                                                 
 dense_2 (Dense)             (None, 512)               1049088   
                                                                 
 dense_3 (Dense)             (None, 1)                 513       
                                                                 
Total params: 24,637,313
Trainable params: 1,049,601
Non-trainable params: 23,587,712
_________________________________________________________________


In [5]:
# test = Image.load_img("/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Aditya-John-400x400.jpeg", target_size=(256, 256))

In [6]:
from PIL import Image
def pre_process_image_data(path):
    for i in os.listdir(path):
        if i.endswith(".jpg"):
            # load the image and resize to 256 by 256
            img = Image.load_img(path + i, target_size=(256, 256))
            # save it to the same folder and overwrite the original
            img.save(path + i)
        elif i.endswith(".png"):
            # load the image and resize to 256 by 256
            img = Image.load_img(path + i, target_size=(256, 256))
            # save it to the same folder and overwrite the original
            img.save(path + i)

        elif i.endswith(".jpeg"):
            # load the image and resize to 256 by 256
            img = Image.load_img(path + i, target_size=(256, 256))
            # save it to the same folder and overwrite the original
            img.save(path + i)
            


In [7]:
test = '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Yuanjing-Zhu-400x400.jpeg'
test = Image.open(test)
test = np.array(test)
test

array([[[111, 109, 114],
        [111, 109, 114],
        [111, 109, 114],
        ...,
        [113, 111, 114],
        [113, 111, 114],
        [113, 111, 114]],

       [[111, 109, 114],
        [111, 109, 114],
        [112, 110, 115],
        ...,
        [113, 111, 114],
        [113, 111, 114],
        [113, 111, 114]],

       [[111, 109, 114],
        [112, 110, 115],
        [112, 110, 115],
        ...,
        [113, 111, 114],
        [113, 111, 114],
        [113, 111, 114]],

       ...,

       [[ 19,  23,  35],
        [ 20,  24,  36],
        [ 21,  25,  37],
        ...,
        [ 15,  24,  33],
        [ 19,  28,  37],
        [ 26,  35,  44]],

       [[ 19,  23,  35],
        [ 20,  24,  36],
        [ 22,  26,  38],
        ...,
        [ 15,  24,  33],
        [ 18,  27,  36],
        [ 25,  34,  43]],

       [[ 19,  23,  35],
        [ 20,  24,  36],
        [ 22,  26,  38],
        ...,
        [ 15,  24,  33],
        [ 18,  27,  36],
        [ 25,  34,  43]]

## function for resize and store a list of array

In [8]:
from PIL import Image
def pre_process_image_data(path):
    lst_img = []
    for i in os.listdir(path):
        # print(i)
        if i[-4:] == "jpeg":
        # print(path + str('/' + i))
            with open(path + str('/' + i), 'rb') as f:
                img = Image.open(f)
                # resize the image to 256 by 256
                img = img.resize((256, 256))
                # save it to the same folder and overwrite the original
                img.save(path + str('/' + i))
                # print("saved")
                # store their array in a list
                lst_img.append(np.array(img))
    return lst_img
            

# def get_array(path):
#     lst_img = []
#     for i in os.listdir(path):

#         if i[-4:] == "jpeg":
#         # print(path + str('/' + i))
#             with open(path + str('/' + i), 'rb') as f:
#                 img = Image.open(f)
#                 # resize the image to 256 by 256
#                 img = img.resize((256, 256))
#                 # save it to the same folder and overwrite the original
#                 img.save(path + str('/' + i))
#                 # print("saved")
#                 # store their array in a list
#                 lst_img.append(np.array(img))
#     return lst_img

# pre_process_image_data(mids24_path)

# # check the resolution of the image
# test = '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Yuanjing-Zhu-400x400.jpeg'
# test = Image.open(test)
# # check the resolution of the image
# test.size



## Process the mids24

In [9]:
# mids24 prediction
mids24_path = "/workspaces/IDS705_ML_Team9/Data/Application/MIDS24"

# use the model to predict the mids24 data: image data
import PIL
from PIL import Image
import os
import numpy as np

# load the image data
pre_process_image_data(mids24_path)


[array([[[111, 109, 114],
         [111, 109, 114],
         [111, 109, 114],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],
 
        [[111, 109, 114],
         [111, 109, 114],
         [112, 110, 115],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],
 
        [[111, 109, 114],
         [112, 110, 115],
         [112, 110, 115],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],
 
        ...,
 
        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 21,  25,  37],
         ...,
         [ 15,  24,  33],
         [ 19,  28,  37],
         [ 26,  35,  44]],
 
        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 22,  26,  38],
         ...,
         [ 15,  24,  33],
         [ 18,  27,  36],
         [ 25,  34,  43]],
 
        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 22,  26,  38],
         ...,
         [ 15,  24,  33],
  

## Prediction

In [10]:
feed = np.array(pre_process_image_data(mids24_path))
feed

array([[[[111, 109, 114],
         [111, 109, 114],
         [111, 109, 114],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],

        [[111, 109, 114],
         [111, 109, 114],
         [112, 110, 115],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],

        [[111, 109, 114],
         [112, 110, 115],
         [112, 110, 115],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],

        ...,

        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 21,  25,  37],
         ...,
         [ 15,  24,  33],
         [ 19,  28,  37],
         [ 26,  35,  44]],

        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 22,  26,  38],
         ...,
         [ 15,  24,  33],
         [ 18,  27,  36],
         [ 25,  34,  43]],

        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 22,  26,  38],
         ...,
         [ 15,  24,  33],
        

In [11]:
# predict the mids24 data
import os
# mids24_data = []
# for i in os.listdir(mids24_path):
#     if i.endswith(".jpg"):
#         img = Image.open(mids24_path + "/" + i)
#         img = np.array(img)
#         mids24_data.append(img)

# convert the list to numpy array
# mids24_data = np.array(mids24_data)

# predict the mids24 data
mids24_pred = model.predict(feed.reshape(-1, 256, 256, 3))

# # save the prediction result
result1 = np.save("mids24_pred.npy", mids24_pred)

2/2 [==============================] - 3s 398ms/step


In [12]:
# get the prediction result
mids24_pred = np.load("mids24_pred.npy")


In [13]:
os.listdir(mids24_path)

['Yuanjing-Zhu-400x400.jpeg',
 'Beibei-Bella-Du-400x400.jpeg',
 'Zhonglin-Wang-400x400.jpeg',
 'Zhanyi-Lin-400x400.jpeg',
 'Dingkun-Yang-400x400.jpeg',
 'Dany-Jabban-400x400.jpeg',
 'Echo-Chen-400x400.jpeg',
 'Xiaoquan-Liu-400x400.jpeg',
 'Andrew-Kroening-400x400.jpeg',
 'Suzy-Anil-400x400.jpeg',
 'Suzanna-Thompson-400x400.jpeg',
 'Genesis-Qu-400x400.jpeg',
 'Song-Young-Oh-400x400.jpeg',
 'Alisa-Tian-400x400.jpeg',
 'Heather-Qiu-400x400.jpeg',
 'Emma-Wang-400x400.jpeg',
 'Aditya-John-400x400.jpeg',
 'Eric-Rios-Soderman-400x400.jpeg',
 'Kashaf-Ali-400x400.jpeg',
 'luo-400x398.jpeg',
 'Scott-Lai-400x400.jpeg',
 'Emmanuel-Ruhamyankaka-400x400.jpeg',
 'Pooja-Kabber-400x400.jpeg',
 'Sukhpreet-Sahota-400x400.jpeg',
 'Ahmed-Ibrahim-400x400.jpeg',
 'Isha-Singh-400x400.jpeg',
 'Kristi-Van-Meter-400x400.jpeg',
 'Pragya-Raghuvanshi-400x400.jpeg',
 'Chloe-Liu-400x400.jpeg',
 'Ya-Yun-Huang-400x400.jpeg',
 'Wafiakmal-Miftah-400x400.jpeg',
 'Pomelo-Wu-400x400.jpeg',
 'README.md',
 'Jenny-Shen-400x400

In [14]:
def get_path(path):
    img_path = []
    for i in os.listdir(path):
        # print(i)
        if i[-4:] == "jpeg":
        # print(path + str('/' + i))
            with open(path + str('/' + i), 'rb') as f:
                img_path.append(path + str('/' + i))
    return img_path

get_path(mids24_path)

['/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Yuanjing-Zhu-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Beibei-Bella-Du-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Zhonglin-Wang-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Zhanyi-Lin-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Dingkun-Yang-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Dany-Jabban-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Echo-Chen-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Xiaoquan-Liu-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Andrew-Kroening-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Suzy-Anil-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Suzanna-Thompson-400x400.jpeg',
 '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Genesis-Qu-400x400.jpeg',
 '/workspaces/ID

In [15]:
len(mids24_pred)
# create a dataframe to store the prediction result and the image name
mids24_pred_df = pd.DataFrame(mids24_pred, columns=["pred"])
mids24_pred_df["image_name"] = get_path(mids24_path)
mids24_pred_df

pred                                         image_name
0    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
1    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
2    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
3    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
4    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
5    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
6    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
7    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
8    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
9    1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
10   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
11   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
12   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
13   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
14   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
15   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
16   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
17   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
18   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
19   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
20   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
21   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
22   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
23   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
24   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
25   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
26   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
27   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
28   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
29   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
30   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
31   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
32   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
33   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
34   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
35   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
36   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...
37   1.0  /workspaces/IDS705_ML_Team9/Data/Application/M...

In [16]:
mids24_pred

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [17]:
# get valuecounts of the prediction result
mids24_pred_df["pred"].value_counts()


pred
1.0    38
Name: count, dtype: int64

## process zip file

In [4]:
real_ai_path = "/workspaces/IDS705_ML_Team9/Data/Application/very_real_ai-faces-20230417T184918Z-001.zip"

# unzip the file
import zipfile
with zipfile.ZipFile(real_ai_path, 'r') as zip_ref:
    zip_ref.extractall("/workspaces/IDS705_ML_Team9/Data/Application/very_real_ai-faces")
    

## Process the dating profile pictures

In [30]:
new_path = "/workspaces/IDS705_ML_Team9/Data/Application/Application_Dating_Profile"
import os
from PIL import Image
import numpy as np

def pre_process_image_data(path):
    lst_img = []
    for i in os.listdir(path):
        # print(i)
        if i[-3:] == "jpg":
        # print(path + str('/' + i))
            with open(path + str('/' + i), 'rb') as f:
                img = Image.open(f)
                # convert the image to RGB
                img = img.convert('RGB')
                # resize the image to 256 by 256
                img = img.resize((256, 256))
                # save it to the same folder and overwrite the original
                img.save(path + str('/' + i))
                # print("saved")
                # store their array in a list
                lst_img.append(np.array(img))
    return lst_img
pre_process_image_data(new_path)

[array([[[ 52,  59,  51],
         [ 57,  64,  56],
         [ 61,  71,  63],
         ...,
         [187, 142, 207],
         [168, 123, 190],
         [152, 109, 178]],
 
        [[ 53,  60,  52],
         [ 56,  63,  55],
         [ 59,  66,  59],
         ...,
         [182, 139, 195],
         [167, 126, 184],
         [158, 119, 176]],
 
        [[ 57,  62,  56],
         [ 57,  64,  57],
         [ 57,  63,  59],
         ...,
         [177, 141, 179],
         [173, 137, 173],
         [172, 138, 173]],
 
        ...,
 
        [[ 67,  81,  56],
         [ 66,  78,  56],
         [ 79,  86,  70],
         ...,
         [ 20,  33,  65],
         [ 27,  40,  74],
         [122, 137, 170]],
 
        [[ 66,  78,  56],
         [ 69,  81,  61],
         [ 84,  90,  76],
         ...,
         [ 13,  28,  61],
         [ 25,  39,  74],
         [ 94, 110, 144]],
 
        [[ 61,  73,  51],
         [ 55,  64,  45],
         [ 74,  80,  66],
         ...,
         [ 14,  29,  62],
  

In [31]:
# new_path = "/workspaces/IDS705_ML_Team9/Data/Application/Application_Dating_Profile"

# def pre_process_image_data(path):
#     lst_img = []
#     for i in os.listdir(path):
#         # print(i)
#         if i[-3:] == "jpg":
#         # print(path + str('/' + i))
#             with open(path + str('/' + i), 'rb') as f:
#                 img = Image.open(f)
#                 # resize the image to 256 by 256
#                 img = img.resize((256, 256))
#                 # save it to the same folder and overwrite the original
#                 img.save(path + str('/' + i))
#                 # print("saved")
#                 # store their array in a list
#                 lst_img.append(np.array(img))
#     return lst_img
# pre_process_image_data(new_path)


In [32]:
# predict the new data
new_data = np.array(pre_process_image_data(new_path))
new_data

# predict the new data
new_pred = model.predict(new_data)

# # save the prediction result
result2 = np.save("new_pred.npy", new_pred)

1/1 [==============================] - 1s 1s/step


In [33]:
# get the prediction result
new_pred = np.load("new_pred.npy")
new_pred

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)