In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_recall_curve
import os

In [25]:
# !pip install tensorflow
# !pip install keras
# !pip install torch


In [26]:
model_rgb_path = "/workspaces/IDS705_ML_Team9/deploy_resnet_model_140K_alldata_rgb.h5"
weights_rgb_path = "/workspaces/IDS705_ML_Team9/deploy_resnet_model_140K_alldata_rgb_weights.h5"

# load the model using h5py
import h5py
model_rgb = h5py.File(model_rgb_path, 'r')
model_rgb_weights = h5py.File(weights_rgb_path, 'r')

# load the model using keras
from keras.models import model_from_json
import tensorflow.keras as keras

# Load the h5 model file
model = keras.models.load_model(model_rgb_path)

# Print the model summary
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 2048)              23587712  
                                                                 
 flatten_1 (Flatten)         (None, 2048)              0         
                                                                 
 dense_2 (Dense)             (None, 512)               1049088   
                                                                 
 dense_3 (Dense)             (None, 1)                 513       
                                                                 
Total params: 24,637,313
Trainable params: 1,049,601
Non-trainable params: 23,587,712
_________________________________________________________________


In [27]:
test = Image.load_img("/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Aditya-John-400x400.jpeg", target_size=(256, 256))

AttributeError: module 'PIL.Image' has no attribute 'load_img'

In [28]:
from PIL import Image
def pre_process_image_data(path):
    for i in os.listdir(path):
        if i.endswith(".jpg"):
            # load the image and resize to 256 by 256
            img = Image.load_img(path + i, target_size=(256, 256))
            # save it to the same folder and overwrite the original
            img.save(path + i)
        elif i.endswith(".png"):
            # load the image and resize to 256 by 256
            img = Image.load_img(path + i, target_size=(256, 256))
            # save it to the same folder and overwrite the original
            img.save(path + i)

        elif i.endswith(".jpeg"):
            # load the image and resize to 256 by 256
            img = Image.load_img(path + i, target_size=(256, 256))
            # save it to the same folder and overwrite the original
            img.save(path + i)
            


In [33]:
test = '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Yuanjing-Zhu-400x400.jpeg'
test = Image.open(test)
test = np.array(test)
test

array([[[108, 106, 111],
        [108, 106, 111],
        [109, 107, 112],
        ...,
        [113, 111, 114],
        [113, 111, 114],
        [113, 111, 114]],

       [[108, 106, 111],
        [109, 107, 112],
        [109, 107, 112],
        ...,
        [113, 111, 114],
        [113, 111, 114],
        [113, 111, 114]],

       [[109, 107, 112],
        [109, 107, 112],
        [110, 108, 113],
        ...,
        [113, 111, 114],
        [113, 111, 114],
        [113, 111, 114]],

       ...,

       [[ 21,  25,  37],
        [ 21,  25,  37],
        [ 22,  26,  38],
        ...,
        [ 20,  28,  39],
        [ 20,  28,  41],
        [ 21,  29,  42]],

       [[ 20,  24,  36],
        [ 21,  25,  37],
        [ 21,  25,  37],
        ...,
        [ 19,  27,  38],
        [ 22,  30,  41],
        [ 24,  32,  43]],

       [[ 19,  23,  35],
        [ 21,  25,  37],
        [ 22,  26,  38],
        ...,
        [ 17,  25,  36],
        [ 21,  29,  40],
        [ 25,  33,  44]]

## function for resize and store a list of array

In [54]:
from PIL import Image
def pre_process_image_data(path):
    lst_img = []
    for i in os.listdir(path):
        # print(i)
        if i[-4:] == "jpeg":
        # print(path + str('/' + i))
            with open(path + str('/' + i), 'rb') as f:
                img = Image.open(f)
                # resize the image to 256 by 256
                img = img.resize((256, 256))
                # save it to the same folder and overwrite the original
                img.save(path + str('/' + i))
                # print("saved")
                # store their array in a list
                lst_img.append(np.array(img))
    return lst_img
            

# def get_array(path):
#     lst_img = []
#     for i in os.listdir(path):

#         if i[-4:] == "jpeg":
#         # print(path + str('/' + i))
#             with open(path + str('/' + i), 'rb') as f:
#                 img = Image.open(f)
#                 # resize the image to 256 by 256
#                 img = img.resize((256, 256))
#                 # save it to the same folder and overwrite the original
#                 img.save(path + str('/' + i))
#                 # print("saved")
#                 # store their array in a list
#                 lst_img.append(np.array(img))
#     return lst_img

# pre_process_image_data(mids24_path)

# # check the resolution of the image
# test = '/workspaces/IDS705_ML_Team9/Data/Application/MIDS24/Yuanjing-Zhu-400x400.jpeg'
# test = Image.open(test)
# # check the resolution of the image
# test.size



## Process the mids24

In [55]:
# mids24 prediction
mids24_path = "/workspaces/IDS705_ML_Team9/Data/Application/MIDS24"

# use the model to predict the mids24 data: image data
import PIL
from PIL import Image
import os
import numpy as np

# load the image data
pre_process_image_data(mids24_path)


[array([[[111, 109, 114],
         [111, 109, 114],
         [111, 109, 114],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],
 
        [[111, 109, 114],
         [111, 109, 114],
         [112, 110, 115],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],
 
        [[111, 109, 114],
         [112, 110, 115],
         [112, 110, 115],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],
 
        ...,
 
        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 21,  25,  37],
         ...,
         [ 15,  24,  33],
         [ 19,  28,  37],
         [ 26,  35,  44]],
 
        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 22,  26,  38],
         ...,
         [ 15,  24,  33],
         [ 18,  27,  36],
         [ 25,  34,  43]],
 
        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 22,  26,  38],
         ...,
         [ 15,  24,  33],
  

## Prediction

In [59]:
feed = np.array(pre_process_image_data(mids24_path))
feed

array([[[[111, 109, 114],
         [111, 109, 114],
         [111, 109, 114],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],

        [[111, 109, 114],
         [111, 109, 114],
         [112, 110, 115],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],

        [[111, 109, 114],
         [112, 110, 115],
         [112, 110, 115],
         ...,
         [113, 111, 114],
         [113, 111, 114],
         [113, 111, 114]],

        ...,

        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 21,  25,  37],
         ...,
         [ 15,  24,  33],
         [ 19,  28,  37],
         [ 26,  35,  44]],

        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 22,  26,  38],
         ...,
         [ 15,  24,  33],
         [ 18,  27,  36],
         [ 25,  34,  43]],

        [[ 19,  23,  35],
         [ 20,  24,  36],
         [ 22,  26,  38],
         ...,
         [ 15,  24,  33],
        

In [62]:
# predict the mids24 data
import os
# mids24_data = []
# for i in os.listdir(mids24_path):
#     if i.endswith(".jpg"):
#         img = Image.open(mids24_path + "/" + i)
#         img = np.array(img)
#         mids24_data.append(img)

# convert the list to numpy array
# mids24_data = np.array(mids24_data)

# predict the mids24 data
mids24_pred = model.predict(feed.reshape(-1, 256, 256, 3))

# # save the prediction result
result1 = np.save("mids24_pred.npy", mids24_pred)

2/2 [==============================] - 2s 253ms/step


In [63]:
# get the prediction result
mids24_pred = np.load("mids24_pred.npy")


In [67]:
os.listdir(mids24_path)

['Yuanjing-Zhu-400x400.jpeg',
 'Beibei-Bella-Du-400x400.jpeg',
 'Zhonglin-Wang-400x400.jpeg',
 'Zhanyi-Lin-400x400.jpeg',
 'Dingkun-Yang-400x400.jpeg',
 'Dany-Jabban-400x400.jpeg',
 'Echo-Chen-400x400.jpeg',
 'Xiaoquan-Liu-400x400.jpeg',
 'Andrew-Kroening-400x400.jpeg',
 'Suzy-Anil-400x400.jpeg',
 'Suzanna-Thompson-400x400.jpeg',
 'Genesis-Qu-400x400.jpeg',
 'Song-Young-Oh-400x400.jpeg',
 'Alisa-Tian-400x400.jpeg',
 'Heather-Qiu-400x400.jpeg',
 'Emma-Wang-400x400.jpeg',
 'Aditya-John-400x400.jpeg',
 'Eric-Rios-Soderman-400x400.jpeg',
 'Kashaf-Ali-400x400.jpeg',
 'luo-400x398.jpeg',
 'Scott-Lai-400x400.jpeg',
 'Emmanuel-Ruhamyankaka-400x400.jpeg',
 'Pooja-Kabber-400x400.jpeg',
 'Sukhpreet-Sahota-400x400.jpeg',
 'Ahmed-Ibrahim-400x400.jpeg',
 'Isha-Singh-400x400.jpeg',
 'Kristi-Van-Meter-400x400.jpeg',
 'Pragya-Raghuvanshi-400x400.jpeg',
 'Chloe-Liu-400x400.jpeg',
 'Ya-Yun-Huang-400x400.jpeg',
 'Wafiakmal-Miftah-400x400.jpeg',
 'Pomelo-Wu-400x400.jpeg',
 'README.md',
 'Jenny-Shen-400x400

In [68]:
len(mids24_pred)
# create a dataframe to store the prediction result and the image name
# mids24_pred_df = pd.DataFrame(mids24_pred, columns=["pred"])
# mids24_pred_df["image_name"] = os.listdir(mids24_path)
# mids24_pred_df

38

In [69]:
mids24_pred

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)